http:
  port: "8081"
  
sfdc:
  username: "krayn1-pqqv@force.com"
  password: "Kraysu123"
  token: "cmCQJxcpRZTgKxXy6gVwCh5Z"
  
file:
  accountsDir: "C:/Users/krayn/Downloads/APDevFundamentals4.3_studentFiles_SP_02jul2021/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"